namespace: monk-n8n

stack:
  metadata:
    defines: metadata
    name: n8n.io - a powerful workflow automation tool
    description: n8n is a free and source-available workflow automation tool - install on prem, download our desktop app or sign up for our cloud service
    tags: automation, workflow
    website: https://n8n.io
    publisher: monk.io
    icon: n8n.png
  defines: process-group
  runnable-list:
    - monk-n8n/n8n
  variables:
    monk_basic_auth_active:
      type: bool
      value: true
    monk_basic_auth_user:
      type: string
      value: monk
    monk_basic_auth_password:
      type: string
      value: monk
    monk_n8n_hostname:
      type: string
      value: n8n.monk.io
    monk_n8n_port:
      type: string
      value: 8085
    monk_n8n_http_protocol:
      type: string
      value: http
    monk_n8n_environment_type:
      type: string
      value: production
    monk_n8n_webhook_url:
      type: string
      value: n8n.monk.io
    monk_n8n_timezone:
      type: string
      value: UTC